version = 1

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["5000"]

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  bootstrap_files = ["5000"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "vue",
    "meteor",
    "angular",
    "angularjs",
    "ember",
    "react"
  ]

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "go"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "ansible"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "scalafmt"
enabled = true